# Generated by Django 5.1.1 on 2024-10-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_purchase', '0002_delete_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.CharField(max_length=50)),
                ('speed', models.CharField(max_length=100)),
                ('installation', models.CharField(default='Free Installation', max_length=100)),
                ('switches_and_routers', models.CharField(default='Free Switches & Routers', max_length=100)),
                ('payment_method', models.CharField(default='Pay, Plug & Play', max_length=100)),
            ],
        ),
    ]
