# Generated by Django 5.1.1 on 2024-10-12 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_purchase', '0004_mpesacallbacks_mpesacalls_mpesapayment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'Plan', 'verbose_name_plural': 'Plans'},
        ),
    ]
