# Generated by Django 5.1.1 on 2024-10-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_purchase', '0005_alter_plan_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(default='no description'),
            preserve_default=False,
        ),
    ]
